// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: swap/v1/pool.proto

package swap

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePoolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token0 string `protobuf:"bytes,1,opt,name=token0,proto3" json:"token0,omitempty"`
	Token1 string `protobuf:"bytes,2,opt,name=token1,proto3" json:"token1,omitempty"`
	Fee    uint32 `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (x *CreatePoolRequest) Reset() {
	*x = CreatePoolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_pool_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePoolRequest) ProtoMessage() {}

func (x *CreatePoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_pool_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePoolRequest.ProtoReflect.Descriptor instead.
func (*CreatePoolRequest) Descriptor() ([]byte, []int) {
	return file_swap_v1_pool_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePoolRequest) GetToken0() string {
	if x != nil {
		return x.Token0
	}
	return ""
}

func (x *CreatePoolRequest) GetToken1() string {
	if x != nil {
		return x.Token1
	}
	return ""
}

func (x *CreatePoolRequest) GetFee() uint32 {
	if x != nil {
		return x.Fee
	}
	return 0
}

type CreatePoolReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreatePoolReply) Reset() {
	*x = CreatePoolReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_pool_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePoolReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePoolReply) ProtoMessage() {}

func (x *CreatePoolReply) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_pool_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePoolReply.ProtoReflect.Descriptor instead.
func (*CreatePoolReply) Descriptor() ([]byte, []int) {
	return file_swap_v1_pool_proto_rawDescGZIP(), []int{1}
}

type UpdatePoolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePoolRequest) Reset() {
	*x = UpdatePoolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_pool_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePoolRequest) ProtoMessage() {}

func (x *UpdatePoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_pool_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePoolRequest.ProtoReflect.Descriptor instead.
func (*UpdatePoolRequest) Descriptor() ([]byte, []int) {
	return file_swap_v1_pool_proto_rawDescGZIP(), []int{2}
}

type UpdatePoolReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePoolReply) Reset() {
	*x = UpdatePoolReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_pool_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePoolReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePoolReply) ProtoMessage() {}

func (x *UpdatePoolReply) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_pool_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePoolReply.ProtoReflect.Descriptor instead.
func (*UpdatePoolReply) Descriptor() ([]byte, []int) {
	return file_swap_v1_pool_proto_rawDescGZIP(), []int{3}
}

type DeletePoolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePoolRequest) Reset() {
	*x = DeletePoolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_pool_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePoolRequest) ProtoMessage() {}

func (x *DeletePoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_pool_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePoolRequest.ProtoReflect.Descriptor instead.
func (*DeletePoolRequest) Descriptor() ([]byte, []int) {
	return file_swap_v1_pool_proto_rawDescGZIP(), []int{4}
}

type DeletePoolReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePoolReply) Reset() {
	*x = DeletePoolReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_pool_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePoolReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePoolReply) ProtoMessage() {}

func (x *DeletePoolReply) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_pool_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePoolReply.ProtoReflect.Descriptor instead.
func (*DeletePoolReply) Descriptor() ([]byte, []int) {
	return file_swap_v1_pool_proto_rawDescGZIP(), []int{5}
}

type GetPoolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token0 string `protobuf:"bytes,1,opt,name=token0,proto3" json:"token0,omitempty"`
	Token1 string `protobuf:"bytes,2,opt,name=token1,proto3" json:"token1,omitempty"`
	Fee    uint32 `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (x *GetPoolRequest) Reset() {
	*x = GetPoolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_pool_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolRequest) ProtoMessage() {}

func (x *GetPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_pool_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolRequest.ProtoReflect.Descriptor instead.
func (*GetPoolRequest) Descriptor() ([]byte, []int) {
	return file_swap_v1_pool_proto_rawDescGZIP(), []int{6}
}

func (x *GetPoolRequest) GetToken0() string {
	if x != nil {
		return x.Token0
	}
	return ""
}

func (x *GetPoolRequest) GetToken1() string {
	if x != nil {
		return x.Token1
	}
	return ""
}

func (x *GetPoolRequest) GetFee() uint32 {
	if x != nil {
		return x.Fee
	}
	return 0
}

type GetPoolReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPoolReply) Reset() {
	*x = GetPoolReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_pool_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPoolReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolReply) ProtoMessage() {}

func (x *GetPoolReply) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_pool_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolReply.ProtoReflect.Descriptor instead.
func (*GetPoolReply) Descriptor() ([]byte, []int) {
	return file_swap_v1_pool_proto_rawDescGZIP(), []int{7}
}

type ListPoolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPoolRequest) Reset() {
	*x = ListPoolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_pool_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoolRequest) ProtoMessage() {}

func (x *ListPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_pool_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoolRequest.ProtoReflect.Descriptor instead.
func (*ListPoolRequest) Descriptor() ([]byte, []int) {
	return file_swap_v1_pool_proto_rawDescGZIP(), []int{8}
}

type ListPoolReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPoolReply) Reset() {
	*x = ListPoolReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_pool_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPoolReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoolReply) ProtoMessage() {}

func (x *ListPoolReply) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_pool_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoolReply.ProtoReflect.Descriptor instead.
func (*ListPoolReply) Descriptor() ([]byte, []int) {
	return file_swap_v1_pool_proto_rawDescGZIP(), []int{9}
}

var File_swap_v1_pool_proto protoreflect.FileDescriptor

var file_swap_v1_pool_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x31, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x66, 0x65, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6f,
	0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13,
	0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6f,
	0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x52, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6f,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x66, 0x65, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a,
	0x0d, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x8e,
	0x03, 0x0a, 0x04, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x56, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61, 0x70,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x3a, 0x01, 0x2a, 0x22, 0x05, 0x2f, 0x70, 0x6f, 0x6f, 0x6c, 0x12,
	0x44, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x1b, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x6f, 0x6f, 0x6c, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x62, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61,
	0x70, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f,
	0x12, 0x1d, 0x2f, 0x70, 0x6f, 0x6f, 0x6c, 0x2f, 0x7b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x7d,
	0x2f, 0x7b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x7d, 0x2f, 0x7b, 0x66, 0x65, 0x65, 0x7d, 0x12,
	0x3e, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x19, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61,
	0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42,
	0x23, 0x0a, 0x08, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x50, 0x01, 0x5a, 0x15, 0x75,
	0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x77, 0x61, 0x70, 0x3b,
	0x73, 0x77, 0x61, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_swap_v1_pool_proto_rawDescOnce sync.Once
	file_swap_v1_pool_proto_rawDescData = file_swap_v1_pool_proto_rawDesc
)

func file_swap_v1_pool_proto_rawDescGZIP() []byte {
	file_swap_v1_pool_proto_rawDescOnce.Do(func() {
		file_swap_v1_pool_proto_rawDescData = protoimpl.X.CompressGZIP(file_swap_v1_pool_proto_rawDescData)
	})
	return file_swap_v1_pool_proto_rawDescData
}

var file_swap_v1_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_swap_v1_pool_proto_goTypes = []any{
	(*CreatePoolRequest)(nil), // 0: api.swap.CreatePoolRequest
	(*CreatePoolReply)(nil),   // 1: api.swap.CreatePoolReply
	(*UpdatePoolRequest)(nil), // 2: api.swap.UpdatePoolRequest
	(*UpdatePoolReply)(nil),   // 3: api.swap.UpdatePoolReply
	(*DeletePoolRequest)(nil), // 4: api.swap.DeletePoolRequest
	(*DeletePoolReply)(nil),   // 5: api.swap.DeletePoolReply
	(*GetPoolRequest)(nil),    // 6: api.swap.GetPoolRequest
	(*GetPoolReply)(nil),      // 7: api.swap.GetPoolReply
	(*ListPoolRequest)(nil),   // 8: api.swap.ListPoolRequest
	(*ListPoolReply)(nil),     // 9: api.swap.ListPoolReply
}
var file_swap_v1_pool_proto_depIdxs = []int32{
	0, // 0: api.swap.Pool.CreatePool:input_type -> api.swap.CreatePoolRequest
	2, // 1: api.swap.Pool.UpdatePool:input_type -> api.swap.UpdatePoolRequest
	4, // 2: api.swap.Pool.DeletePool:input_type -> api.swap.DeletePoolRequest
	6, // 3: api.swap.Pool.GetPool:input_type -> api.swap.GetPoolRequest
	8, // 4: api.swap.Pool.ListPool:input_type -> api.swap.ListPoolRequest
	1, // 5: api.swap.Pool.CreatePool:output_type -> api.swap.CreatePoolReply
	3, // 6: api.swap.Pool.UpdatePool:output_type -> api.swap.UpdatePoolReply
	5, // 7: api.swap.Pool.DeletePool:output_type -> api.swap.DeletePoolReply
	7, // 8: api.swap.Pool.GetPool:output_type -> api.swap.GetPoolReply
	9, // 9: api.swap.Pool.ListPool:output_type -> api.swap.ListPoolReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_swap_v1_pool_proto_init() }
func file_swap_v1_pool_proto_init() {
	if File_swap_v1_pool_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_swap_v1_pool_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePoolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_pool_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePoolReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_pool_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdatePoolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_pool_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdatePoolReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_pool_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeletePoolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_pool_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeletePoolReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_pool_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetPoolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_pool_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetPoolReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_pool_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListPoolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_pool_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListPoolReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_swap_v1_pool_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swap_v1_pool_proto_goTypes,
		DependencyIndexes: file_swap_v1_pool_proto_depIdxs,
		MessageInfos:      file_swap_v1_pool_proto_msgTypes,
	}.Build()
	File_swap_v1_pool_proto = out.File
	file_swap_v1_pool_proto_rawDesc = nil
	file_swap_v1_pool_proto_goTypes = nil
	file_swap_v1_pool_proto_depIdxs = nil
}
