// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: swap/v1/swap.proto

package swap

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSwapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token0          string `protobuf:"bytes,1,opt,name=token0,proto3" json:"token0,omitempty"`
	Token1          string `protobuf:"bytes,2,opt,name=token1,proto3" json:"token1,omitempty"`
	Fee             uint32 `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
	Recipient       string `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	ZeroForOne      bool   `protobuf:"varint,5,opt,name=zeroForOne,proto3" json:"zeroForOne,omitempty"`
	AmountSpecified string `protobuf:"bytes,6,opt,name=amountSpecified,proto3" json:"amountSpecified,omitempty"`
	PriceLimit      string `protobuf:"bytes,7,opt,name=priceLimit,proto3" json:"priceLimit,omitempty"`
}

func (x *CreateSwapRequest) Reset() {
	*x = CreateSwapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_swap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSwapRequest) ProtoMessage() {}

func (x *CreateSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_swap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSwapRequest.ProtoReflect.Descriptor instead.
func (*CreateSwapRequest) Descriptor() ([]byte, []int) {
	return file_swap_v1_swap_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSwapRequest) GetToken0() string {
	if x != nil {
		return x.Token0
	}
	return ""
}

func (x *CreateSwapRequest) GetToken1() string {
	if x != nil {
		return x.Token1
	}
	return ""
}

func (x *CreateSwapRequest) GetFee() uint32 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *CreateSwapRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *CreateSwapRequest) GetZeroForOne() bool {
	if x != nil {
		return x.ZeroForOne
	}
	return false
}

func (x *CreateSwapRequest) GetAmountSpecified() string {
	if x != nil {
		return x.AmountSpecified
	}
	return ""
}

func (x *CreateSwapRequest) GetPriceLimit() string {
	if x != nil {
		return x.PriceLimit
	}
	return ""
}

type CreateSwapReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateSwapReply) Reset() {
	*x = CreateSwapReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_swap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSwapReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSwapReply) ProtoMessage() {}

func (x *CreateSwapReply) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_swap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSwapReply.ProtoReflect.Descriptor instead.
func (*CreateSwapReply) Descriptor() ([]byte, []int) {
	return file_swap_v1_swap_proto_rawDescGZIP(), []int{1}
}

type UpdateSwapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSwapRequest) Reset() {
	*x = UpdateSwapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_swap_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSwapRequest) ProtoMessage() {}

func (x *UpdateSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_swap_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSwapRequest.ProtoReflect.Descriptor instead.
func (*UpdateSwapRequest) Descriptor() ([]byte, []int) {
	return file_swap_v1_swap_proto_rawDescGZIP(), []int{2}
}

type UpdateSwapReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSwapReply) Reset() {
	*x = UpdateSwapReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_swap_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSwapReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSwapReply) ProtoMessage() {}

func (x *UpdateSwapReply) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_swap_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSwapReply.ProtoReflect.Descriptor instead.
func (*UpdateSwapReply) Descriptor() ([]byte, []int) {
	return file_swap_v1_swap_proto_rawDescGZIP(), []int{3}
}

type DeleteSwapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSwapRequest) Reset() {
	*x = DeleteSwapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_swap_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSwapRequest) ProtoMessage() {}

func (x *DeleteSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_swap_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSwapRequest.ProtoReflect.Descriptor instead.
func (*DeleteSwapRequest) Descriptor() ([]byte, []int) {
	return file_swap_v1_swap_proto_rawDescGZIP(), []int{4}
}

type DeleteSwapReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSwapReply) Reset() {
	*x = DeleteSwapReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_swap_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSwapReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSwapReply) ProtoMessage() {}

func (x *DeleteSwapReply) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_swap_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSwapReply.ProtoReflect.Descriptor instead.
func (*DeleteSwapReply) Descriptor() ([]byte, []int) {
	return file_swap_v1_swap_proto_rawDescGZIP(), []int{5}
}

type GetSwapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSwapRequest) Reset() {
	*x = GetSwapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_swap_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwapRequest) ProtoMessage() {}

func (x *GetSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_swap_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwapRequest.ProtoReflect.Descriptor instead.
func (*GetSwapRequest) Descriptor() ([]byte, []int) {
	return file_swap_v1_swap_proto_rawDescGZIP(), []int{6}
}

type GetSwapReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSwapReply) Reset() {
	*x = GetSwapReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_swap_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSwapReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwapReply) ProtoMessage() {}

func (x *GetSwapReply) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_swap_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwapReply.ProtoReflect.Descriptor instead.
func (*GetSwapReply) Descriptor() ([]byte, []int) {
	return file_swap_v1_swap_proto_rawDescGZIP(), []int{7}
}

type ListSwapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSwapRequest) Reset() {
	*x = ListSwapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_swap_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSwapRequest) ProtoMessage() {}

func (x *ListSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_swap_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSwapRequest.ProtoReflect.Descriptor instead.
func (*ListSwapRequest) Descriptor() ([]byte, []int) {
	return file_swap_v1_swap_proto_rawDescGZIP(), []int{8}
}

type ListSwapReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSwapReply) Reset() {
	*x = ListSwapReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swap_v1_swap_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSwapReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSwapReply) ProtoMessage() {}

func (x *ListSwapReply) ProtoReflect() protoreflect.Message {
	mi := &file_swap_v1_swap_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSwapReply.ProtoReflect.Descriptor instead.
func (*ListSwapReply) Descriptor() ([]byte, []int) {
	return file_swap_v1_swap_proto_rawDescGZIP(), []int{9}
}

var File_swap_v1_swap_proto protoreflect.FileDescriptor

var file_swap_v1_swap_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x22, 0xdd,
	0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x66, 0x65, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70,
	0x69, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x7a, 0x65, 0x72, 0x6f, 0x46, 0x6f, 0x72, 0x4f,
	0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x7a, 0x65, 0x72, 0x6f, 0x46, 0x6f,
	0x72, 0x4f, 0x6e, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x70,
	0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x11,
	0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x77, 0x61, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11,
	0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x77, 0x61, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x77,
	0x61, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xd5, 0x02, 0x0a, 0x04, 0x53, 0x77, 0x61, 0x70,
	0x12, 0x44, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x77, 0x61, 0x70, 0x12, 0x1b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x77, 0x61,
	0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x77, 0x61, 0x70, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x0a,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x77, 0x61, 0x70, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x77, 0x61, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77,
	0x61, 0x70, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x53, 0x77, 0x61, 0x70, 0x12, 0x18, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x77, 0x61, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77,
	0x61, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x3e, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x77, 0x61, 0x70, 0x12, 0x19, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x77, 0x61, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61,
	0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42,
	0x23, 0x0a, 0x08, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x50, 0x01, 0x5a, 0x15, 0x75,
	0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x77, 0x61, 0x70, 0x3b,
	0x73, 0x77, 0x61, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_swap_v1_swap_proto_rawDescOnce sync.Once
	file_swap_v1_swap_proto_rawDescData = file_swap_v1_swap_proto_rawDesc
)

func file_swap_v1_swap_proto_rawDescGZIP() []byte {
	file_swap_v1_swap_proto_rawDescOnce.Do(func() {
		file_swap_v1_swap_proto_rawDescData = protoimpl.X.CompressGZIP(file_swap_v1_swap_proto_rawDescData)
	})
	return file_swap_v1_swap_proto_rawDescData
}

var file_swap_v1_swap_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_swap_v1_swap_proto_goTypes = []any{
	(*CreateSwapRequest)(nil), // 0: api.swap.CreateSwapRequest
	(*CreateSwapReply)(nil),   // 1: api.swap.CreateSwapReply
	(*UpdateSwapRequest)(nil), // 2: api.swap.UpdateSwapRequest
	(*UpdateSwapReply)(nil),   // 3: api.swap.UpdateSwapReply
	(*DeleteSwapRequest)(nil), // 4: api.swap.DeleteSwapRequest
	(*DeleteSwapReply)(nil),   // 5: api.swap.DeleteSwapReply
	(*GetSwapRequest)(nil),    // 6: api.swap.GetSwapRequest
	(*GetSwapReply)(nil),      // 7: api.swap.GetSwapReply
	(*ListSwapRequest)(nil),   // 8: api.swap.ListSwapRequest
	(*ListSwapReply)(nil),     // 9: api.swap.ListSwapReply
}
var file_swap_v1_swap_proto_depIdxs = []int32{
	0, // 0: api.swap.Swap.CreateSwap:input_type -> api.swap.CreateSwapRequest
	2, // 1: api.swap.Swap.UpdateSwap:input_type -> api.swap.UpdateSwapRequest
	4, // 2: api.swap.Swap.DeleteSwap:input_type -> api.swap.DeleteSwapRequest
	6, // 3: api.swap.Swap.GetSwap:input_type -> api.swap.GetSwapRequest
	8, // 4: api.swap.Swap.ListSwap:input_type -> api.swap.ListSwapRequest
	1, // 5: api.swap.Swap.CreateSwap:output_type -> api.swap.CreateSwapReply
	3, // 6: api.swap.Swap.UpdateSwap:output_type -> api.swap.UpdateSwapReply
	5, // 7: api.swap.Swap.DeleteSwap:output_type -> api.swap.DeleteSwapReply
	7, // 8: api.swap.Swap.GetSwap:output_type -> api.swap.GetSwapReply
	9, // 9: api.swap.Swap.ListSwap:output_type -> api.swap.ListSwapReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_swap_v1_swap_proto_init() }
func file_swap_v1_swap_proto_init() {
	if File_swap_v1_swap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_swap_v1_swap_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateSwapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_swap_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateSwapReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_swap_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateSwapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_swap_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateSwapReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_swap_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteSwapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_swap_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteSwapReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_swap_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetSwapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_swap_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetSwapReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_swap_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListSwapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swap_v1_swap_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListSwapReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_swap_v1_swap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swap_v1_swap_proto_goTypes,
		DependencyIndexes: file_swap_v1_swap_proto_depIdxs,
		MessageInfos:      file_swap_v1_swap_proto_msgTypes,
	}.Build()
	File_swap_v1_swap_proto = out.File
	file_swap_v1_swap_proto_rawDesc = nil
	file_swap_v1_swap_proto_goTypes = nil
	file_swap_v1_swap_proto_depIdxs = nil
}
