// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"uniswap/internal/dao/internal"
)

// internalFeeGrowthGlobalDao is internal type for wrapping internal DAO implements.
type internalFeeGrowthGlobalDao = *internal.FeeGrowthGlobalDao

// feeGrowthGlobalDao is the data access object for table fee_growth_global.
// You can define custom methods on it to extend its functionality as you wish.
type feeGrowthGlobalDao struct {
	internalFeeGrowthGlobalDao
}

var (
	// FeeGrowthGlobal is globally public accessible object for table fee_growth_global operations.
	FeeGrowthGlobal = feeGrowthGlobalDao{
		internal.NewFeeGrowthGlobalDao(),
	}
)

// Fill with you ideas below.
