// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"uniswap/internal/dao/internal"
)

// internalLiquidityDao is internal type for wrapping internal DAO implements.
type internalLiquidityDao = *internal.LiquidityDao

// liquidityDao is the data access object for table liquidity.
// You can define custom methods on it to extend its functionality as you wish.
type liquidityDao struct {
	internalLiquidityDao
}

var (
	// Liquidity is globally public accessible object for table liquidity operations.
	Liquidity = liquidityDao{
		internal.NewLiquidityDao(),
	}
)

// Fill with you ideas below.
