// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"uniswap/internal/dao/internal"
)

// internalObservationDao is internal type for wrapping internal DAO implements.
type internalObservationDao = *internal.ObservationDao

// observationDao is the data access object for table observation.
// You can define custom methods on it to extend its functionality as you wish.
type observationDao struct {
	internalObservationDao
}

var (
	// Observation is globally public accessible object for table observation operations.
	Observation = observationDao{
		internal.NewObservationDao(),
	}
)

// Fill with you ideas below.
