// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"uniswap/internal/dao/internal"
)

// internalPoolDao is internal type for wrapping internal DAO implements.
type internalPoolDao = *internal.PoolDao

// poolDao is the data access object for table pool.
// You can define custom methods on it to extend its functionality as you wish.
type poolDao struct {
	internalPoolDao
}

var (
	// Pool is globally public accessible object for table pool operations.
	Pool = poolDao{
		internal.NewPoolDao(),
	}
)

// Fill with you ideas below.
