// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"uniswap/internal/dao/internal"
)

// internalSlot0Dao is internal type for wrapping internal DAO implements.
type internalSlot0Dao = *internal.Slot0Dao

// slot0Dao is the data access object for table slot0.
// You can define custom methods on it to extend its functionality as you wish.
type slot0Dao struct {
	internalSlot0Dao
}

var (
	// Slot0 is globally public accessible object for table slot0 operations.
	Slot0 = slot0Dao{
		internal.NewSlot0Dao(),
	}
)

// Fill with you ideas below.
