// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"uniswap/internal/dao/internal"
)

// internalTickBitmapDao is internal type for wrapping internal DAO implements.
type internalTickBitmapDao = *internal.TickBitmapDao

// tickBitmapDao is the data access object for table tick_bitmap.
// You can define custom methods on it to extend its functionality as you wish.
type tickBitmapDao struct {
	internalTickBitmapDao
}

var (
	// TickBitmap is globally public accessible object for table tick_bitmap operations.
	TickBitmap = tickBitmapDao{
		internal.NewTickBitmapDao(),
	}
)

// Fill with you ideas below.
