// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"uniswap/internal/dao/internal"
)

// internalTickDao is internal type for wrapping internal DAO implements.
type internalTickDao = *internal.TickDao

// tickDao is the data access object for table tick.
// You can define custom methods on it to extend its functionality as you wish.
type tickDao struct {
	internalTickDao
}

var (
	// Tick is globally public accessible object for table tick operations.
	Tick = tickDao{
		internal.NewTickDao(),
	}
)

// Fill with you ideas below.
